// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { localDb } from '@/lib/db/local-client';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const realSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// In Electron the preload script exposes window.drovo; use the local SQLite
// client in that context and the real Supabase client everywhere else.
const isElectron =
  typeof window !== 'undefined' && typeof (window as any).drovo !== 'undefined';

export const supabase = isElectron ? (localDb as unknown as typeof realSupabase) : realSupabase;
